application: escribepami
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /favicon\.png
  static_files: favicon.png
  upload: favicon\.png

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: latest
